In [0]:
#print function 만들어보기
def print_info(name="none", age="29"):
  print("Name : ", name)
  print("Age : ", age)
  return;

print_info(name="miki",age=50)
print_info(name = "janne",)

Name :  miki
Age :  50
Name :  janne
Age :  29

In [0]:
def Sum(arg1, arg2):
  result = arg1 + arg2
  print("Inside the function : ", result)
  return result;
total = Sum(10,20)
print("Outside the function : ",total)

Inside the function :  30
Outside the function :  30

*** TRY ***

In [0]:
#함수 안의 function 이 고정값으로 반환됨 - 흔히하는 실수
def changeme(fmylist):
  fmylist = [1,2,3,4];
  print("value inside the function : ", fmylist)
  return fmylist;
mylist = [10,20,30]
mylist2 = changeme(mylist)
print("value outside the function : ", mylist2)

value inside the function :  [1, 2, 3, 4]
value outside the function :  [1, 2, 3, 4]

In [0]:
def changeme(fmylist2):
  fmylist2.append([1,2,3,4]);
  print("value inside the function : ", fmylist2)
  return fmylist2;
mylist3 = [10,20,30]
mylist4 = changeme(mylist)
print("value outside the function : ", mylist4)

value inside the function :  [10, 20, 30, [1, 2, 3, 4], (1, 2, 3, 4)]
value outside the function :  [10, 20, 30, [1, 2, 3, 4], (1, 2, 3, 4)]

In [0]:
def printinfo(fname, fage=35):
  return fname,fage;
name, age = printinfo(fage=50, fname="miki")
print(name + "," + str(age))
print(name, age)

miki,50
miki 50

*** Parameter ***

In [10]:
def print_return_tuple(arg1, *vartuple):
  print("inside arg1 is : ", arg1)
  for var in vartuple:
    print("Inside vartuple is :", var)
  return vartuple;

print_return_tuple(10)      #for문에서 vartuple 자체가 없어서 안돌아가므로, 함수의 첫 문장만 실행되고 에러는 안남

#함수 파라미터와 계산식이 매칭되므로, 70은 vartuple에 들어가지 않음 -> 해당 줄의 결과값에서 70이 제외됨
#파라미터에 들어왔다고 무조건 리턴으로 되는 것은 아님
out_tuple = print_return_tuple(70,60,50)
print(out_tuple)

inside arg1 is :  10
inside arg1 is :  70
Inside vartuple is : 60
Inside vartuple is : 50
(60, 50)

In [12]:
#일반적인 print와 같은 방식의 함수
def print_return_tuple2(*vartuple2):
  for var2 in vartuple2:
    print("Inside vartuple is :", var2)
  return vartuple2;

out_tuple2 = print_return_tuple2(70,60,50)
print(out_tuple2)

Inside vartuple is : 70
Inside vartuple is : 60
Inside vartuple is : 50
(70, 60, 50)

*** TRY 2 ***

In [13]:
def functionA (*var_args01, **var_args02):
  print(var_args01, type(var_args01))
  print(var_args02, type(var_args02))
functionA(1,2,3,4,5,6,a=2,b=4,c=5)

(1, 2, 3, 4, 5, 6) <class 'tuple'>
{'a': 2, 'b': 4, 'c': 5} <class 'dict'>
ERROR! Session/line number was not unique in database. History logging moved to new session 62

In [19]:
args_list = [1,2,3,4]
args_dict = { 'a':10, 'b':20}
functionA(*args_list, **args_dict)

(1, 2, 3, 4) <class 'tuple'>
{'a': 10, 'b': 20} <class 'dict'>

*** Lambda ***\
반복적으로 사용하지만,\
함수 만들기에는 비효율적일 때\
단순화된 함수 정도로 사용
- 입력 parameter만 있으면 됨
- 파라미터가 적용되는 영역은 ':'으로 정함
- (+) kotlin 에서는 다르게 적용되는 lambda

In [1]:
sumLam = lambda arg1, arg2 : arg1 + arg2;
print("Value of total : ", sumLam(10,20))

Value of total :  30